extends: "default"

rules:
  comments:
    min-spaces-from-content: 1
  comments-indentation: "enable"
  document-start: "disable"
  document-end: "disable"
  empty-values: "enable"
  indentation:
    spaces: 2
    check-multi-line-strings: true
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  quoted-strings:
    quote-type: "double"
  line-length:
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
