name: Continuous Delivery Template
on:
  workflow_call:
    inputs:
      publish:
        description: Specify whether publish a release
        type: boolean
        required: true
      pattern:
        description: Specify which files include in a release via globs
        type: string
        required: false
        default: "*"
      tag:
        description: Specify which tag use for a release
        type: string
        required: false
        default: "v1.0"
      versioning:
        description: Specify which versioning type use for a repository
        type: string
        required: false
        default: semantic
      script_path:
        description: Specify which script path use for a repository
        type: string
        required: false
        default: ci-helpers

jobs:
  publish-release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: check tag input
      run: bash "${{ inputs.script_path }}/scripts/check_tag_format.sh" "${{ inputs.tag }}" "${{ inputs.versioning }}"
    - name: publish
      if: inputs.publish == true && success()
      uses: ncipollo/release-action@v1.9.0
      with:
        artifacts: ${{ inputs.pattern }}
        bodyFile: README.md
        tag: ${{ inputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
